services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: team-workload-app:1.0.0
    container_name: team-workload-app
    ports:
      - "8080:80"
    restart: unless-stopped

